### ISSUE TITLE
why i can't add a language switcher ?

### ISSUE THREAD

**Issue by fatheyabdelslam** [dougwollison/nlingual#9]
i can't Find Any Language switcher in the plugin ? 
why

**Comment by dougwollison** [comment]
To the public facing side of the site? Right now it only offers nav items (under Language Links) to be added to menus allowing you to switch to a particular language.

**Comment by fatheyabdelslam** [comment]
Ok i hope to found this feature in the future
What o loved about this plugin is that i can choose the slug in URL i loved it
But i believe is that there is two more bugs
1 when i forcing all URL slug in default language then go to home page with out typing the language slug it give me 404 error instand of redirect me to the home page with language slug

2 -when uninstalling the pluging i give me deleting but with out any action

**Comment by dougwollison** [comment]
I'll see about testing out issue 1, as for 2, could you reword that? I'm not following what you mean.

**Comment by dougwollison** [comment]
Okay, so I'm testing out issue 1 on a site with what should be a similar setup, and I'm not getting the 404, it redirects properly.

Are you using the latest version (2.7.0)? There is a change whatever was causing it was fixed with that update.

Just a thought, do you have the Homepage setting under Reading Settings to "A Static Page" or "Your Latest Posts"? It just occurred to me I probably never tested how this handles things when homepage is just a list of posts (every site I've developed this on has a dedicated homepage).
